# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d860d2ea5fe7e61aae49d83c36047afda09f809c1fc8fdf17da59a150b207ac1d6a08250eb431abc560425b02fbef2d9c2fe245f527bbe8d46af70a1a00a35b0

test:
  secret_key_base: 0264731e694d45e6a6614f9e155ad54949e71e5125c6eb383ce741ee4725d5f19f7803e8a9bbdb096e2d2b8ea88415c8fce28332e4e8b54289a70315bbaa0837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
