IrresponsibleModule:
  enabled: false
NestedIterators:
  max_allowed_nesting: 2
DuplicateMethodCall:
  max_calls: 2
TooManyStatements:
  max_statements: 10
InstanceVariableAssumption:
  enabled: false
TooManyInstanceVariables:
  max_instance_variables: 6
FeatureEnvy:
  exclude:
    - "ParticipateController#user_params"
    - "ParticipateController#process_contents"
