Documentation:
  Enabled: false
AllCops:
  DisplayCopNames: true
Metrics/LineLength:
  Max: 100
Rails/HasAndBelongsToMany:
  Description: 'Prefer has_many :through to has_and_belongs_to_many.'
  Enabled: false
